{{- if .Values.identity_account_mapper.enabled }}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "ph-ee-identity-account-mapper"
  labels:
    app: ph-ee-identity-account-mapper
spec:
  replicas: {{ .Values.identity_account_mapper.replicas }}
  selector:
    matchLabels:
      app: ph-ee-identity-account-mapper
  template:
    metadata:
      labels:
        app: ph-ee-identity-account-mapper
      annotations:
        {{- if .Values.identity_account_mapper.deployment.annotations }}
          {{ toYaml .Values.identity_account_mapper.deployment.annotations | indent 8 }}
          {{- end }}
    spec:
      containers:
        - name: ph-ee-identity-account-mapper
          image: "{{ .Values.identity_account_mapper.image }}:{{ .Values.identity_account_mapper.imageTag }}"
          imagePullPolicy: "{{ .Values.identity_account_mapper.imagePullPolicy }}"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /oauth/token_key
              port: 5000
          env:
            - name: "LOGGING_LEVEL_ROOT"
              value: "{{ .Values.identity_account_mapper.LOGGING_LEVEL_ROOT }}"
            - name: "async.core-pool-size"
              value: "{{ .Values.identity_account_mapper.async.core_pool_size }}"
            - name: "async.max-pool-size"
              value: "{{ .Values.identity_account_mapper.async.max_pool_size }}"
            - name: "async.queue-capacity"
              value: "{{ .Values.identity_account_mapper.async.queue_capacity }}"
            - name: "account_validation_enabled"
              value: "{{ .Values.identity_account_mapper.account_validation_enabled }}"
            - name: "account_validator_connector"
              value: "{{ .Values.identity_account_mapper.account_validator_connector }}"
            - name: "gsma-connector.contactpoint"
              value: "{{ .Values.identity_account_mapper.gsma_connector.contactpoint }}"
            - name: "mojaloop-connector.contactpoint"
              value: "{{ .Values.identity_account_mapper.mojaloop_connector.contactpoint }}"
          resources:
            limits:
              memory: "{{ .Values.identity_account_mapper.limits.memory }}"
              cpu: "{{ .Values.identity_account_mapper.limits.cpu }}"
            requests:
              memory: "{{ .Values.identity_account_mapper.requests.memory }}"
              cpu: "{{ .Values.identity_account_mapper.requests.cpu }}"

  {{- end }}
