{{- if .Values.enabled }}

apiVersion: {{ .Values.deployment.apiVersion }}
kind: Deployment
metadata:
  name: "ph-ee-identity-account-mapper"
  labels:
    app: ph-ee-identity-account-mapper
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ph-ee-identity-account-mapper
  template:
    metadata:
      labels:
        app: ph-ee-identity-account-mapper
      annotations:
        {{- if .Values.deployment.annotations }}
          {{ toYaml .Values.deployment.annotations | indent 8 }}
          {{- end }}
    spec:
      containers:
        - name: ph-ee-identity-account-mapper
          image: "{{ .Values.image }}:{{ .Values.imagetag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - containerPort: 8080
          env:
            - name: "LOGGING_LEVEL_ROOT"
              value: "{{ .Values.LOGGING_LEVEL_ROOT }}"
            - name: "async.core-pool-size"
              value: "{{ .Values.async.core_pool_size }}"
            - name: "async.max-pool-size"
              value: "{{ .Values.async.max_pool_size }}"
            - name: "async.queue-capacity"
              value: "{{ .Values.async.queue_capacity }}"
            - name: "account_validation_enabled"
              value: "{{ .Values.account_validation_enabled }}"
            - name: "account_validator_connector"
              value: "{{ .Values.account_validator_connector }}"
            - name: "gsma-connector.contactpoint"
              value: "{{ .Values.gsma_connector.contactpoint }}"
            - name: "mojaloop-connector.contactpoint"
              value: "{{ .Values.mojaloop_connector.contactpoint }}"
          resources:
            limits:
              memory: "{{ .Values.limits.memory }}"
              cpu: "{{ .Values.limits.cpu }}"
            requests:
              memory: "{{ .Values.requests.memory }}"
              cpu: "{{ .Values.requests.cpu }}"

  {{- end }}