{{- if .Values.identity_account_mapper.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-identity-account-mapper
  annotations:
  {{- if .Values.identity_account_mapper.ingress.annotations }}
  {{ toYaml .Values.identity_account_mapper.ingress.annotations | indent 4 }}
  {{- end }}
spec:
  rules:
    - host: "{{ .Values.identity_account_mapper.hostname }}"
      http:
        paths:
          - path: "{{ .Values.identity_account_mapper.ingress.path }}"
            pathType: Prefix
            backend:
  {{- if .Values.identity_account_mapper.ingress.backend }}
  {{ toYaml .Values.identity_account_mapper.ingress.backend | indent 14 }}
  {{- end }}

tls:
  - hosts:
      - "{{ .Values.wildcardhostname }}"
    secretName: "{{ .Values.tls }}"
  {{- end }}