deployment:
  apiVersion: "apps/v1"

ingress:
  enabled: true
  apiVersion: networking.k8s.io/v1

service:
  apiVersion: "v1"

secret:
  apiVersion: "v1"

configmap:
  apiVersion: "v1"


zeebe:
  broker:
    contactpoint: "zeebe-zeebe-gateway:26500"
zeebe-cluster-helm:
  enabled: true
  global:
    elasticsearch:
      host: "ph-ee-elasticsearch"
  image:
    repository: camunda/zeebe
    tag: 1.1.0

  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  JavaOpts: "-Xms8g -Xmx8g -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:MaxRAMPercentage=25.0 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+PrintFlagsFinal"

  elasticsearch:
    enabled: false
  kibana:
    enabled: false

  extraInitContainers: |
    - name: init-ph-ee-kafka-exporter
      image: busybox:1.28
      command: ['/bin/sh', '-c']
      args: ['wget -O /exporters/ph-ee-kafka-exporter.jar "https://paymenthub-ee-dev.s3.us-east-2.amazonaws.com/jars/exporter-1.0.0-SNAPSHOT.jar"; ls -al /exporters/']
      volumeMounts:
      - name: exporters
        mountPath: /exporters/

zeebe-operate-helm:
  enabled: true
  image:
    repository: camunda/operate
    tag: 1.1.0
  global:
    elasticsearch:
      host: "ph-ee-elasticsearch"
      clusterName: "ph-ee-elasticsearch"
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
    path: /
    host: operate.sandbox.mifos.io
    tls:
      enabled: true

elasticsearch:
  enabled: true

  #Single Node Solution
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=100s"
  protocol: http
  master:
    readinessProbe:
      httpGet:
        allow-insecure: true
        username: elastic
        password: "{{ .Env.ELASTIC_PASSWORD }}"
        path: /_cluster/health?wait_for_status=yellow&timeout=5s
        port: 9200
      initialDelaySeconds: 30
  data:
    readinessProbe:
      httpGet:
        allow-insecure: true
        username: elastic
        password: "{{ .Env.ELASTIC_PASSWORD }}"
        path: /_cluster/health?wait_for_status=yellow&timeout=5s
        port: 9200
      initialDelaySeconds: 30



  # Shrink default JVM heap.
  esJavaOpts: "-Xmx512m -Xms512m"

  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "1024M"
    limits:
      cpu: "1000m"
      memory: "1024M"
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "gp2"
    resources:
      requests:
        storage: 10Gi

kibana:
  enabled: true
  readinessProbe:
    initialDelaySeconds: 45
    timeoutSeconds: 15
    successThreshold: 1
  protocol: http
  ingress:
    enabled: true
    className: "nginx"
    pathtype: "Prefix"
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: analytics.sandbox.mifos.io
        paths:
          - path: /
    #tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

operations:
  enabled: true

idmappermysql:
  enabled: true
  fullnameOverride: "idmappermysql"
  image:
    tag: "5.7"
    debug: false
  auth:
    database: "tenants"
    username: "idmapper"
    password: "password"
    rootPassword: "ethieTieCh8ahv"
  initdbScripts:
    setup.sql: |-
      CREATE DATABASE IF NOT EXISTS IdentityAccountMapper;
      GRANT ALL ON *.* TO 'root'@'%';
      GRANT ALL PRIVILEGES ON IdentityAccountMapper.* TO 'idmapper';


kafka:
  enabled: true
  replicas: 1
  image: "spotify/kafka"
  imagePullPolicy: "Always"
  advertised:
    host: "kafka"
    port: "9092"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations:
      deployTime: "{{ .Values.deployTime }}"

identity_account_mapper:
  enabled: true
  image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-identity-account-mapper"
  imagetag: "latest"
  imagePullPolicy: "Always"
  hostname: "identity.sandbox.fynarfin.io"
  ingress:
    enabled: true
    hostname: "identity.sandbox.fynarfin.io"
    path: "/"
    wildcardhostname: "*.sandbox.fynarfin.io"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "200m"
      memory: "0.5Gi"
  async:
    core_pool_size: "10"
    max_pool_size: "10"
    queue_capacity: "100"
  account_validation_enabled: "false"
  account_validator_connector: "gsma"
  gsma_connector:
    contactpoint: ""
  mojaloop_connector:
    contactpoint: ""
